name: Daily Naver Report

on:
  schedule:
    # 매일 한국시간 오전 8시 30분
    - cron: "30 23 * * *"

  # Actions 화면에서 수동 실행 가능
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        run: naver_powerlink_shopping_adgroup_report.py
